name: cinam

on:
  push:
    branches: [ "cinam" ]

  workflow_dispatch:

jobs:
  nam_build:
    runs-on: ubuntu-latest

    steps:
      - name: nam remote exec ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY }}" >  ~/.ssh/id_rsa
          
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa nam@34.143.236.100 sh -c "
            set -x  # print the executed  
          
            echo '--- git clone code ve neu chua clone'
            mkdir -p ~/_/cinam
          
            if [ ! -d ~/_/cinam/todb17_danhsachlop/.git ]; then
              cd      ~/_/cinam ; git clone git@github.com:namgivu/todb17_danhsachlop.git  
            else
              echo 'Repo da ton tai, bo qua git clone'
            fi

            echo
            echo '--- git pull code ve de lay moi nhat'
            cd ~/_/cinam/todb17_danhsachlop 
            git checkout cinam ; git fetch origin ; git reset --hard origin/cinam

            echo
            echo '--- chay composeup'
            cd ~/_/cinam/todb17_danhsachlop 
            webapp_port=8022 ./composeup.sh
          "
